services:
  - type: web
    name: portfolio-backend
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_RATE_LIMIT_WINDOW
        value: "900000"
      - key: API_RATE_LIMIT_MAX
        value: "100"
      - key: CACHE_TTL
        value: "300000"
      - key: LOG_LEVEL
        value: info
